---
- hosts: ec2
  gather_facts: false
  become: true
  user: ec2-user
  vars:
    - ansible_ssh_private_key_file: "ec2_instance_key.pem"
  roles:
    - web_server
  post_tasks:
     - include_tasks: web_server/tests/test.yml
